name: Download and Release OpenJDK

on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: 'JDK version (11, 17, or 21)'
        required: true
        default: '17'
      platforms:
        description: 'Comma-separated list of platforms (linux/amd64, linux/arm64, windows/amd64)'
        required: true
        default: 'linux/amd64, linux/arm64, windows/amd64'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            archive: tar.gz
            arch: x64
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/linux/x64/jdk/hotspot/normal/adoptium
          - platform: linux/arm64
            runner: ubuntu-latest
            archive: tar.gz
            arch: aarch64
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/linux/aarch64/jdk/hotspot/normal/adoptium
          - platform: windows/amd64
            runner: windows-latest
            archive: zip
            arch: x64
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/windows/x64/jdk/hotspot/normal/adoptium

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create workspace folders
        run: mkdir -p ${{ github.workspace }}/output ${{ github.workspace }}/openjdk

      - name: Download JDK Binary from Adoptium
        run: |
          echo "Downloading OpenJDK version ${{ inputs.jdk_version }} for ${{ matrix.platform }}"
          curl -L "${{ matrix.download_url }}" -o openjdk.${{ matrix.archive }}

      - name: Extract JDK
        run: |
          if [[ "${{ matrix.archive }}" == "tar.gz" ]]; then
            tar -xzf openjdk.tar.gz -C openjdk
          else
            unzip openjdk.zip -d openjdk
          fi

      - name: Repackage JDK
        run: |
          OUTPUT=output/openjdk-${{ inputs.jdk_version }}-${{ matrix.platform }}
          if [[ "${{ matrix.archive }}" == "tar.gz" ]]; then
            tar -czf ${OUTPUT}.tar.gz -C openjdk .
          else
            7z a -tzip ${OUTPUT}.zip ./openjdk/*
          fi

      - name: Generate checksum
        run: |
          cd output
          sha256sum * > SHA256SUMS.txt

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: jdk-${{ inputs.jdk_version }}-$(date +%Y%m%d)
          name: OpenJDK ${{ inputs.jdk_version }} Release $(date +%Y-%m-%d)
          files: |
            output/*.tar.gz
            output/*.zip
            output/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
