name: Download and Release OpenJDK

on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: 'JDK version (11, 17, or 21)'
        required: true
        default: '17'
      platforms:
        description: 'Comma-separated list of platforms (linux/amd64, linux/arm64, windows/x64)'
        required: true
        default: 'linux/amd64,linux/arm64,windows/x64'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            archive: tar.gz
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/linux/x64/jdk/hotspot/normal/adoptium
          - platform: linux/arm64
            archive: tar.gz
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/linux/aarch64/jdk/hotspot/normal/adoptium
          - platform: windows/x64
            archive: zip
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/windows/x64/jdk/hotspot/normal/adoptium

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JDK Binary from Adoptium
        run: |
          echo "Downloading OpenJDK ${{ github.event.inputs.jdk_version }} for ${{ matrix.platform }}"
          curl -L ${{ matrix.download_url }} -o openjdk_bundle.${{ matrix.archive }}

      - name: Rename JDK Binary for Release
        id: rename_file
        run: |
          # 生成安全的平台名称（替换斜杠为连字符）
          SAFE_PLATFORM=$(echo "${{ matrix.platform }}" | tr '/' '-')
          OUTPUT_NAME=openjdk-${{ github.event.inputs.jdk_version }}-${SAFE_PLATFORM}.${{ matrix.archive }}
          mv openjdk_bundle.${{ matrix.archive }} $OUTPUT_NAME
          echo "OUTPUT_NAME=$OUTPUT_NAME" >> $GITHUB_ENV
          echo "SAFE_PLATFORM=$SAFE_PLATFORM" >> $GITHUB_ENV  # 保存安全平台名称

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # 使用安全的平台名称（无斜杠）
          name: jdk-${{ github.event.inputs.jdk_version }}-${{ env.SAFE_PLATFORM }}
          path: ${{ env.OUTPUT_NAME }}
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts/

      - name: Display structure of downloaded files
        run: |
          echo "Contents of downloaded artifacts:"
          ls -R ./artifacts/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.jdk_version }}
          name: "OpenJDK ${{ github.event.inputs.jdk_version }} Release"
          body: |
            Automated release of OpenJDK ${{ github.event.inputs.jdk_version }} for multiple platforms.
            Includes builds for:
            ${{ github.event.inputs.platforms }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.jdk_version }}
          files: |
            ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}