name: Download and Release OpenJDK

on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: 'JDK version (11, 17, or 21)'
        required: true
        default: '17'
      platforms:
        description: 'Comma-separated list of platforms (linux/amd64, linux/arm64, windows/amd64)'
        required: true
        default: 'linux/amd64,linux/arm64,windows/amd64'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            archive: tar.gz
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/linux/x64/jdk/hotspot/normal/adoptium
          - platform: linux/arm64
            archive: tar.gz
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/linux/aarch64/jdk/hotspot/normal/adoptium
          - platform: windows/amd64
            archive: zip
            download_url: https://api.adoptium.net/v3/binary/latest/${{ github.event.inputs.jdk_version }}/ga/windows/x64/jdk/hotspot/normal/adoptium

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JDK Binary from Adoptium
        run: |
          echo "Downloading OpenJDK ${{ github.event.inputs.jdk_version }} for ${{ matrix.platform }}"
          curl -L ${{ matrix.download_url }} -o openjdk_bundle.${{ matrix.archive }}

      - name: Rename JDK Binary for Release
        run: |
          SAFE_PLATFORM=$(echo "${{ matrix.platform }}" | sed 's/\//-/g')
          OUTPUT_NAME=openjdk-${{ github.event.inputs.jdk_version }}-${SAFE_PLATFORM}.${{ matrix.archive }}
          mv openjdk_bundle.${{ matrix.archive }} $OUTPUT_NAME

      - name: Upload Artifact to Release
        uses: actions/upload-artifact@v4
        with:
          name: $OUTPUT_NAME
          path: $OUTPUT_NAME
